spring:
  application:
    name: monthly-budget-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/monthlydb}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: ${JWT_SECRET:devDefaultSecret12345678901234567890123456789012}
    expiration: ${JWT_EXPIRATION:86400000}