spring:
  application:
    name: monthly-budget-api

  datasource:
    url: ${DB_URL:jdbc:h2:mem:monthlydb;DB_CLOSE_DELAY=-1}
    driverClassName: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: ${JWT_SECRET:devDefaultSecret12345678901234567890123456789012}
    expiration: ${JWT_EXPIRATION:86400000}